version: '3.8'

services:
  # Database for Core Services
  postgres-db:
    image: postgres:15-alpine
    container_name: banking-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sarthak_admin
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: banking_core
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banking-network

  # Message Broker for Async Event Communication
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: banking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - banking-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: banking-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:2181,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - banking-network

  # 1. Authentication Service (JWT Provider)
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/banking_core
      SPRING_DATASOURCE_USERNAME: sarthak_admin
      SPRING_DATASOURCE_PASSWORD: supersecurepassword
    networks:
      - banking-network

  # 2. Account Management Service
  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/banking_core
    networks:
      - banking-network

  # 3. Transaction Service (Produces Events to Kafka)
  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/banking_core
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:2181
    networks:
      - banking-network

  # API Gateway Routing Everything
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - auth-service
      - account-service
      - transaction-service
    networks:
      - banking-network

volumes:
  pgdata:

networks:
  banking-network:
    driver: bridge