server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    # Docker environment variables standard check, fallback points to the docker network coordinates
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/banking_core}
    username: ${SPRING_DATASOURCE_USERNAME:sarthak_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:supersecurepassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        # Points to Account Service's event package
        spring.json.value.default.type: "com.banking.account_service.dto.TransactionEvent"

jwt:
  secret: ${JWT_SECRET:BankingAppSuperSecretKey2024ForJWTSigningMustBe256BitsLong!!}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always